// GENERATED by 3PyScheme/tools/gen_cpp_unicode_tables.scm -- DO NOT EDIT.
// Source: pyscheme host char/string ops, Unicode 16.0.0.

#pragma once
#include <cstdint>

// Unicode case mapping + classification, matching pyscheme's host
// char/string operations (Unicode 16.0.0).
namespace unicode
{
// Full case mapping of cp into out[0..n); returns n (1..3).  Unmapped
// codepoints yield themselves (n==1).  char-level ops use n==1 only.
int upcase(char32_t cp, char32_t out[3]);
int downcase(char32_t cp, char32_t out[3]);
int foldcase(char32_t cp, char32_t out[3]);
bool is_alpha(char32_t cp);   // host str.isalpha
bool is_digit(char32_t cp);   // host str.isdigit
bool is_space(char32_t cp);   // host str.isspace
bool is_upper(char32_t cp);   // host str.isupper
bool is_lower(char32_t cp);   // host str.islower
const char* version();   // Unicode database version, e.g. "16.0.0"
}
