// GENERATED by 3PyScheme/tools/gen_unicode_tables.py -- DO NOT EDIT.
// Source: Python 3.14.5, Unicode 16.0.0.

#pragma once
#include <cstdint>

// Unicode case mapping + classification, matching pyscheme's host-Python
// str/char methods (Unicode 16.0.0).
namespace unicode
{
// Full case mapping of cp into out[0..n); returns n (1..3).  Unmapped
// codepoints yield themselves (n==1).  char-level ops use n==1 only.
int upcase(char32_t cp, char32_t out[3]);
int downcase(char32_t cp, char32_t out[3]);
int foldcase(char32_t cp, char32_t out[3]);
bool is_alpha(char32_t cp);   // Python str.isalpha
bool is_digit(char32_t cp);   // Python str.isdigit
bool is_space(char32_t cp);   // Python str.isspace
bool is_upper(char32_t cp);   // Python str.isupper
bool is_lower(char32_t cp);   // Python str.islower
}
